# Introdccion a Numpy

[Numpy](https://numpy.org/doc/stable/) es una libreria para la computacion con python.
* Proporiona Arrays N-Dimensionales.
* Implementa funciones matematicas sofisticadas
* proporciona herramientas para integrar C/C++ y Fortran.
* Proporciona mecanismos para facilitar la realizacion de las tareas relacionadas con algebra lineal o numeros aleatorios

## Imports

In [1]:
import numpy as np

## Arrays
Un **array** es una estructura de datos que consiste en una coleccion de elementos (valores o variables), cada uno identificdo por almenos un indice o clave. Un array se almacena de modo que la posicion de cada elemento se pueda calcular a partir de su tupla de inidce, mediante una formula matematica. El tipo mas simple de array es un array lineal tambien llamado array unidimensional

En Numpy:
* Cada dimension se denomina **axis**
* El numero de dimensiones se denomina **rank**
* La lista de dimensiones con su correspondiente longitud se denomina **shape**
* El numero total de elementos (multiplicacion de la longitud de las dimensiones) a esto se denomina **size**

In [2]:
# Array cuyos valores son todos 0.
a= np.zeros((2, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

_a_ es una array:

* con dos **axis**, el primero de longitud 2 y el segundo de longitud 4.
* Con un **rank** igual a 2
* Con un **shape** igual a (2,4)
* Con un **size** igual a 8

In [3]:
a.shape

(2, 4)

In [4]:
a.ndim

2

In [5]:
a.size

8

## Creacion de Arrays


In [9]:
# Array cuyos valores son todos 0
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [10]:
# Array cuyos valores son todos 1
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [11]:
# Array cuyos valores son todos el valor indicado como segundo parametro de la funcion
np.full((2,3,4),8)

array([[[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]],

       [[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]]])